---
# tasks file for octoprint

- name: Install octoprint
  include: octoprint.yml
  when: install_octoprint and not uninstall_octoprint

- name: Install webcam streamer
  include: webcam.yml
  when: install_webcam and not uninstall_octoprint

- name: Remove octoprint and webcam
  include: uninstall.yml
  when: uninstall_octoprint
